name: Documentation
description: Request to update documentation or fix typos
title: "[Docs] - "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: "# Update documentation"
  - type: textarea
    id: docs
    attributes:
      label: What changes would you like to make in the documentation?
      description: Please explain the issue and what the change should be
    validations:
      required: true
