name: Feature request
description: Request for feature
title: "[Feature] - "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: "# Feature request"
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
      description: Please provide a detailed description for the new feature.
