name: General report
description: This is a general issue that does not fit in the other categories
title: "[General] - "
body:
  - type: markdown
    attributes:
      value: "# General"
  - type: textarea
    id: description
    attributes:
      label: What general issue would you like to create?
      description: Please be as detailed as possible. Include code snippets or screenshots if necessary.
