name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm ci

      - name: Configure Git
        run: |
          git config user.name camperbot
          git config user.email ${{ secrets.CAMPERBOT_EMAIL }}
          git remote set-url origin https://camperbot:${{ secrets.CAMPERBOT_PAT }}@github.com/freeCodeCamp/Developer_Quiz_Site.git

      - name: Run Deploy Script
        run: pnpm run deploy
