name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name camperbot
          git config user.email ${{ secrets.CAMPERBOT_EMAIL }}
          git remote set-url origin https://camperbot:${{ secrets.CAMPERBOT_PAT }}@github.com/freeCodeCamp/Developer_Quiz_Site.git

      - name: Run Deploy Script
        run: npm run deploy
