name: Lint
on:
  push:
    branches-ignore:
      - "renovate/**"
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Lint Source Files
        run: |
          echo npm version $(npm -v)
          pnpm install --frozen-lockfile
          pnpm run lint
